uint8 cmd
uint8 CMD_TAKEOFF=1   # Команда на взлет. В массив data необходимо внести 1 число, означающее целевую высоту в метрах
uint8 CMD_LAND=2      # Команда на посадку. Массив data остается нетронут
uint8 CMD_MOVE=3      # Команда перемещния на заданные параметры смещения и вращения по рысканию. В массив data входят четыре числа, первые три x, y, z [метры] - смещения по осям системы координат ROS (x - вперед, y - влево, z - вверх) и четвертое число - вращение [радианы] по рысканию относительно текущего положения (положительное - против часовой, отрицательное - по часовой)
float32[] data
---
uint8 result
uint8 RES_SUCCESS=4
uint8 RES_FAILED=5